#!/usr/bin/env python
"""
Copyright 2011 Wordnik, Inc.
 
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0
 
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class TestData:
    """

    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            'addressList': 'List<Address>',
            'stateProvinceList': 'List<StateProvince>',
            'countryList': 'List<Country>',
            'addressRequestList': 'List<AddressRequest>',
            'customerResponseList': 'List<CustomerResponse>',
            'creditCardResponseList': 'List<CreditCardResponse>',
            'customerRequestList': 'List<CustomerRequest>',
            'creditCardRequestList': 'List<CreditCardRequest>',
            'addressResponseList': 'List<AddressResponse>',
            'productResponseList': 'List<ProductResponse>',
            'pricingPlanResponseList': 'List<PricingPlanResponse>',
            'productFamilyResponseList': 'List<ProductFamilyResponse>',
            'productItemRequestList': 'List<ProductItemRequest>',
            'productPricingPlanPaymentScheduleRequestList': 'List<ProductPricingPlanPaymentScheduleRequest>',
            'productItemResponseList': 'List<ProductItemResponse>',
            'productMeteredPriceRequestList': 'List<ProductMeteredPriceRequest>',
            'productRequestList': 'List<ProductRequest>',
            'productFamilyRequestList': 'List<ProductFamilyRequest>',
            'productMeteredPriceResponseList': 'List<ProductMeteredPriceResponse>',
            'pricingPlanRequestList': 'List<PricingPlanRequest>',
            'productPricingPlanPaymentScheduleResponseList': 'List<ProductPricingPlanPaymentScheduleResponse>',
            'siteSummaryList': 'List<SiteSummary>',
            'reportIntValueItemList': 'List<ReportIntValueItem>',
            'activeSubscriptionsCountResponseList': 'List<ActiveSubscriptionsCountResponse>',
            'totalSubscribersCountResponseList': 'List<TotalSubscribersCountResponse>',
            'revenueAmountList': 'List<RevenueAmount>',
            'productsSignupsList': 'List<ProductsSignups>',
            'productsRevenuesList': 'List<ProductsRevenues>',
            'reportDecimalValueItemList': 'List<ReportDecimalValueItem>',
            'todayNewSubscribersCountResponseList': 'List<TodayNewSubscribersCountResponse>',
            'statementList': 'List<Statement>',
            'statementDetailList': 'List<StatementDetail>',
            'subscriptionRequestList': 'List<SubscriptionRequest>',
            'subscriptionResponseList': 'List<SubscriptionResponse>',
            'serviceResultList': 'List<ServiceResult>',
            'currencyList': 'List<Currency>',
            'cancellationRequestList': 'List<CancellationRequest>',
            'subscriptionItemHistoryResponseList': 'List<SubscriptionItemHistoryResponse>',
            'subscriptionItemResponseList': 'List<SubscriptionItemResponse>',
            'transactionResponseList': 'List<TransactionResponse>',
            'subscriptionItemRequestList': 'List<SubscriptionItemRequest>',
            'chargeRequestList': 'List<ChargeRequest>',
            'eventDataList': 'List<EventData>'
        }



        # 
        self.addressList = None # List<Address>


        # 
        self.stateProvinceList = None # List<StateProvince>


        # 
        self.countryList = None # List<Country>


        # 
        self.addressRequestList = None # List<AddressRequest>


        # 
        self.customerResponseList = None # List<CustomerResponse>


        # 
        self.creditCardResponseList = None # List<CreditCardResponse>


        # 
        self.customerRequestList = None # List<CustomerRequest>


        # 
        self.creditCardRequestList = None # List<CreditCardRequest>


        # 
        self.addressResponseList = None # List<AddressResponse>


        # 
        self.productResponseList = None # List<ProductResponse>


        # 
        self.pricingPlanResponseList = None # List<PricingPlanResponse>


        # 
        self.productFamilyResponseList = None # List<ProductFamilyResponse>


        # 
        self.productItemRequestList = None # List<ProductItemRequest>


        # 
        self.productPricingPlanPaymentScheduleRequestList = None # List<ProductPricingPlanPaymentScheduleRequest>


        # 
        self.productItemResponseList = None # List<ProductItemResponse>


        # 
        self.productMeteredPriceRequestList = None # List<ProductMeteredPriceRequest>


        # 
        self.productRequestList = None # List<ProductRequest>


        # 
        self.productFamilyRequestList = None # List<ProductFamilyRequest>


        # 
        self.productMeteredPriceResponseList = None # List<ProductMeteredPriceResponse>


        # 
        self.pricingPlanRequestList = None # List<PricingPlanRequest>


        # 
        self.productPricingPlanPaymentScheduleResponseList = None # List<ProductPricingPlanPaymentScheduleResponse>


        # 
        self.siteSummaryList = None # List<SiteSummary>


        # 
        self.reportIntValueItemList = None # List<ReportIntValueItem>


        # 
        self.activeSubscriptionsCountResponseList = None # List<ActiveSubscriptionsCountResponse>


        # 
        self.totalSubscribersCountResponseList = None # List<TotalSubscribersCountResponse>


        # 
        self.revenueAmountList = None # List<RevenueAmount>


        # 
        self.productsSignupsList = None # List<ProductsSignups>


        # 
        self.productsRevenuesList = None # List<ProductsRevenues>


        # 
        self.reportDecimalValueItemList = None # List<ReportDecimalValueItem>


        # 
        self.todayNewSubscribersCountResponseList = None # List<TodayNewSubscribersCountResponse>


        # 
        self.statementList = None # List<Statement>


        # 
        self.statementDetailList = None # List<StatementDetail>


        # 
        self.subscriptionRequestList = None # List<SubscriptionRequest>


        # 
        self.subscriptionResponseList = None # List<SubscriptionResponse>


        # 
        self.serviceResultList = None # List<ServiceResult>


        # 
        self.currencyList = None # List<Currency>


        # 
        self.cancellationRequestList = None # List<CancellationRequest>


        # 
        self.subscriptionItemHistoryResponseList = None # List<SubscriptionItemHistoryResponse>


        # 
        self.subscriptionItemResponseList = None # List<SubscriptionItemResponse>


        # 
        self.transactionResponseList = None # List<TransactionResponse>


        # 
        self.subscriptionItemRequestList = None # List<SubscriptionItemRequest>


        # 
        self.chargeRequestList = None # List<ChargeRequest>


        # 
        self.eventDataList = None # List<EventData>

