#!/usr/bin/env python
"""
AppsAPI.py
Copyright 2011 Wordnik, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/../')
import model

class AppsAPI(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    def GetAllApplications(self, ):
        """GetAllApplications
        Args:
        Return:
            list<ApplicationResponse> -- an instance of ApplicationResponse"""

        # Parse inputs
        resourcePath = '/apps/{format}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'GET'

        queryParams = {}
        headerParams = {}



        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
        if not response:
            return None


        # Create output objects if the response has more than one object
        responseObjects = []
        for responseObject in response:
          responseObjects.append(self.apiClient.deserialize(responseObject,
                                                         'ApplicationResponse'))
        return responseObjects
    def GetCompanyApplications(self, ):
        """GetCompanyApplications
        Args:
        Return:
            list<ApplicationInCompanyResponse> -- an instance of ApplicationInCompanyResponse"""

        # Parse inputs
        resourcePath = '/apps/bycompany/{format}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'GET'

        queryParams = {}
        headerParams = {}



        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
        if not response:
            return None


        # Create output objects if the response has more than one object
        responseObjects = []
        for responseObject in response:
          responseObjects.append(self.apiClient.deserialize(responseObject,
                                                         'ApplicationInCompanyResponse'))
        return responseObjects
    def GetCompanyApplicationById(self, applicationId, ):
        """GetCompanyApplicationById
        Args:
            applicationId -- application Id

        Return:
            ApplicationInCompanyResponse -- an instance of ApplicationInCompanyResponse"""

        # Parse inputs
        resourcePath = '/apps/{applicationId}.{format}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'GET'

        queryParams = {}
        headerParams = {}


        if applicationId != None:
            resourcePath = resourcePath.replace('{applicationId}', self.apiClient.toPathValue(applicationId))


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response,
                                                    'ApplicationInCompanyResponse')
        return responseObject


    def GetCompanyApplicationByName(self, appName, ):
        """GetCompanyApplicationByName
        Args:
            appName -- app Name

        Return:
            ApplicationInCompanyResponse -- an instance of ApplicationInCompanyResponse"""

        # Parse inputs
        resourcePath = '/apps/[{appName}].{format}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'GET'

        queryParams = {}
        headerParams = {}


        if appName != None:
            resourcePath = resourcePath.replace('{appName}', self.apiClient.toPathValue(appName))


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response,
                                                    'ApplicationInCompanyResponse')
        return responseObject


    def GetApplicationCurrentPlan(self, applicationId, ):
        """GetApplicationCurrentPlan
        Args:
            applicationId -- application Id

        Return:
            ApplicationPlan -- an instance of ApplicationPlan"""

        # Parse inputs
        resourcePath = '/apps/plan/{applicationId}.{format}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'GET'

        queryParams = {}
        headerParams = {}


        if applicationId != None:
            resourcePath = resourcePath.replace('{applicationId}', self.apiClient.toPathValue(applicationId))


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response,
                                                    'ApplicationPlan')
        return responseObject


    def SetApplicationStatus(self, applicationId, status, ):
        """SetApplicationStatus
        Args:
            applicationId -- application Id
            status -- status

"""

        # Parse inputs
        resourcePath = '/apps/{applicationId}/{status}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'PUT'

        queryParams = {}
        headerParams = {}


        if applicationId != None:
            resourcePath = resourcePath.replace('{applicationId}', self.apiClient.toPathValue(applicationId))
        if status != None:
            resourcePath = resourcePath.replace('{status}', self.apiClient.toPathValue(status))


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
