#!/usr/bin/env python
"""
ProductfamilyAPI.py
Copyright 2011 Wordnik, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/../')
import model

class ProductfamilyAPI(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    def GetProductFamilies(self, siteSubdomain, isArchived, pageNumber, pageSize, ):
        """GetProductFamilies
        Args:
            siteSubdomain -- site Subdomain
            isArchived -- is Archived
            pageNumber -- page number
            pageSize -- page size

        Return:
            list<ProductFamilyResponse> -- an instance of ProductFamilyResponse"""

        # Parse inputs
        resourcePath = '/productfamily/{siteSubdomain}/{format}?isArchived={isArchived}&pageNumber={pageNumber}&pageSize={pageSize}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'GET'

        queryParams = {}
        headerParams = {}


        if siteSubdomain != None:
            resourcePath = resourcePath.replace('{siteSubdomain}', self.apiClient.toPathValue(siteSubdomain))
        if isArchived != None:
            resourcePath = resourcePath.replace('{isArchived}', self.apiClient.toPathValue(isArchived))
        if pageNumber != None:
            resourcePath = resourcePath.replace('{pageNumber}', self.apiClient.toPathValue(pageNumber))
        if pageSize != None:
            resourcePath = resourcePath.replace('{pageSize}', self.apiClient.toPathValue(pageSize))


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
        if not response:
            return None


        # Create output objects if the response has more than one object
        responseObjects = []
        for responseObject in response:
          responseObjects.append(self.apiClient.deserialize(responseObject,
                                                         'ProductFamilyResponse'))
        return responseObjects
    def GetProductFamilyById(self, productFamilyId, ):
        """GetProductFamilyById
        Args:
            productFamilyId -- product Family Id

        Return:
            ProductFamilyResponse -- an instance of ProductFamilyResponse"""

        # Parse inputs
        resourcePath = '/productfamily/{productFamilyId}.{format}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'GET'

        queryParams = {}
        headerParams = {}


        if productFamilyId != None:
            resourcePath = resourcePath.replace('{productFamilyId}', self.apiClient.toPathValue(productFamilyId))


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response,
                                                    'ProductFamilyResponse')
        return responseObject


    def GetProductFamilyByName(self, siteSubdomain, productFamilyName, ):
        """GetProductFamilyByName
        Args:
            siteSubdomain -- site Subdomain
            productFamilyName -- product Family Name

        Return:
            ProductFamilyResponse -- an instance of ProductFamilyResponse"""

        # Parse inputs
        resourcePath = '/productfamily/{siteSubdomain}/[{productFamilyName}].{format}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'GET'

        queryParams = {}
        headerParams = {}


        if siteSubdomain != None:
            resourcePath = resourcePath.replace('{siteSubdomain}', self.apiClient.toPathValue(siteSubdomain))
        if productFamilyName != None:
            resourcePath = resourcePath.replace('{productFamilyName}', self.apiClient.toPathValue(productFamilyName))


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response,
                                                    'ProductFamilyResponse')
        return responseObject


    def AddProductFamily(self, postData, ):
        """AddProductFamily
        Args:
            postData -- new product Family

        Return:
            ProductFamilyResponse -- an instance of ProductFamilyResponse"""

        # Parse inputs
        resourcePath = '/productfamily/{format}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'POST'

        queryParams = {}
        headerParams = {}



        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response,
                                                    'ProductFamilyResponse')
        return responseObject


    def UpdateProductFamily(self, postData, productFamilyId, ):
        """UpdateProductFamily
        Args:
            postData -- updated Family
            productFamilyId -- product Family Id

        Return:
            ProductFamilyResponse -- an instance of ProductFamilyResponse"""

        # Parse inputs
        resourcePath = '/productfamily/{productFamilyId}.{format}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'PUT'

        queryParams = {}
        headerParams = {}


        if productFamilyId != None:
            resourcePath = resourcePath.replace('{productFamilyId}', self.apiClient.toPathValue(productFamilyId))


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response,
                                                    'ProductFamilyResponse')
        return responseObject


    def DeleteProductFamily(self, productFamilyId, ):
        """DeleteProductFamily
        Args:
            productFamilyId -- product Family Id

"""

        # Parse inputs
        resourcePath = '/productfamily/{productFamilyId}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}


        if productFamilyId != None:
            resourcePath = resourcePath.replace('{productFamilyId}', self.apiClient.toPathValue(productFamilyId))


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
    def ArchiveProductFamily(self, productFamilyId, ):
        """ArchiveProductFamily
        Args:
            productFamilyId -- product Family Id

"""

        # Parse inputs
        resourcePath = '/productfamily/archive/{productFamilyId}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'PUT'

        queryParams = {}
        headerParams = {}


        if productFamilyId != None:
            resourcePath = resourcePath.replace('{productFamilyId}', self.apiClient.toPathValue(productFamilyId))


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
    def ActivateProductFamily(self, productFamilyId, activateProducts, ):
        """ActivateProductFamily
        Args:
            productFamilyId -- product Family Id
            activateProducts -- activate Products

"""

        # Parse inputs
        resourcePath = '/productfamily/activate/{productFamilyId}?activateProducts={activateProducts}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'PUT'

        queryParams = {}
        headerParams = {}


        if productFamilyId != None:
            resourcePath = resourcePath.replace('{productFamilyId}', self.apiClient.toPathValue(productFamilyId))
        if activateProducts != None:
            resourcePath = resourcePath.replace('{activateProducts}', self.apiClient.toPathValue(activateProducts))


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
